package com.home.conts;

public enum CustomerTable {
	customerCode(0), 
	customerName(1), 
	createTime(2), 
	certificateNumber(3), 
	certificateDate(4),
	certificateAddress(5),
	taxNumber(6), 
	budgetRegister(7), 
	telefone(8), 
	fax(9), 
	email(10), 
	socialAddress(11), 
	businessAddress(12), 
	adviser(13),
	director(14), 
	directorMobile(12), 
	directorBirthday(12), 
	directorDomicile(12), 
	sellMan(12), 
	sellManMobile(12), 
	budgetOriginal(12), 
	otherBusiness(12), 
	customer1Level1(12), 
	customer1Phone(12), 
	customer1Percent(12), 
	customer2Level1(12), 
	customer2Phone(12), 
	customer2Percent(12), 
	customer3Level1(12), 
	customer3Phone(12), 
	customer3Percent(12), 
	customer4Level1(12), 
	customer4Phone(12), 
	customer4Percent(12), 
	customer5Level1(12), 
	customer5Phone(12), 
	customer5Percent(12), 
	revenue1(12), 
	revenue2(12), 
	percentProvide1(12), 
	percentProvide2(12), 
	percentProvide3(12), 
	percentProvide4(12), 
	productSell(12), 
	product1Hot(12), 
	product2Hot(12), 
	product3Hot(12), 
	product4Hot(12), 
	product5Hot(12), 
	product6Hot(12), 
	farmProduct1(12), 
	farmProduct1Session(12), 
	farmProduct2(12), 
	farmProduct2Session(12), 
	farmProduct3(12), 
	farmProduct3Session(12), 
	farmProduct4(12), 
	farmProduct4Session(12), 
	userFullName(13);
	
	private int value;
	private CustomerTable(int value){
		this.value = value;
	}
	public int value(){
		return this.value;
	}
}
