package com.home.model;

// Generated Sep 19, 2016 11:34:17 PM by Hibernate Tools 4.3.1

/**
 * ContactType generated by hbm2java
 */
public class ContactType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String contactTypeName;

	public ContactType() {
	}

	public ContactType(String contactTypeName) {
		this.contactTypeName = contactTypeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContactTypeName() {
		return this.contactTypeName;
	}

	public void setContactTypeName(String contactTypeName) {
		this.contactTypeName = contactTypeName;
	}

}
