package com.home.model;

// Generated Jan 12, 2016 11:20:58 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String customerCode;
	private String customerName;
	private String adviser;
	private String createTime;
	private String certificateNumber;
	private String certificateDate;
	private String certificateAddress;
	private String taxNumber;
	private Integer budgetRegister;
	private String telefone;
	private String fax;
	private String email;
	private String socialAddress;
	private String companyAddress;
	private String lawyer;
	private String director;
	private String directorMobile;
	private String directorBirthday;
	private String directorDomicile;
	private String sellMan;
	private String sellManMobile;
	private Integer budgetOriginal;
	private String otherBusiness;
	private String customer1Level1;
	private String customer1Phone;
	private String customer1Percent;
	private String customer2Level1;
	private String customer2Phone;
	private String customer2Percent;
	private String customer3Level1;
	private String customer3Phone;
	private String customer3Percent;
	private String customer4Level1;
	private String customer4Phone;
	private String customer4Percent;
	private String customer5Level1;
	private String customer5Phone;
	private String customer5Percent;
	private String revenue1;
	private String revenue2;
	private String percentProvide1;
	private String percentProvide2;
	private String percentProvide3;
	private String percentProvide4;
	private String productSell;
	private String product1Hot;
	private String product2Hot;
	private String product3Hot;
	private String product4Hot;
	private String product5Hot;
	private String product6Hot;
	private String farmProduct1;
	private String farmProduct1Session;
	private String farmProduct2;
	private String farmProduct2Session;
	private String farmProduct3;
	private String farmProduct3Session;
	private String farmProduct4;
	private String farmProduct4Session;
	private Integer totalVipCustomer;
	private Set<PromotionCustomer> promotionCustomers = new HashSet<PromotionCustomer>(
			0);

	public Customer() {
	}

	public Customer(String customerCode, String customerName, String adviser,
			String createTime, String certificateNumber,
			String certificateDate, String certificateAddress,
			String taxNumber, Integer budgetRegister, String telefone,
			String fax, String email, String socialAddress,
			String companyAddress, String lawyer, String director,
			String directorMobile, String directorBirthday,
			String directorDomicile, String sellMan, String sellManMobile,
			Integer budgetOriginal, String otherBusiness,
			String customer1Level1, String customer1Phone,
			String customer1Percent, String customer2Level1,
			String customer2Phone, String customer2Percent,
			String customer3Level1, String customer3Phone,
			String customer3Percent, String customer4Level1,
			String customer4Phone, String customer4Percent,
			String customer5Level1, String customer5Phone,
			String customer5Percent, String revenue1, String revenue2,
			String percentProvide1, String percentProvide2,
			String percentProvide3, String percentProvide4, String productSell,
			String product1Hot, String product2Hot, String product3Hot,
			String product4Hot, String product5Hot, String product6Hot,
			String farmProduct1, String farmProduct1Session,
			String farmProduct2, String farmProduct2Session,
			String farmProduct3, String farmProduct3Session,
			String farmProduct4, String farmProduct4Session,
			Integer totalVipCustomer, Set<PromotionCustomer> promotionCustomers) {
		this.customerCode = customerCode;
		this.customerName = customerName;
		this.adviser = adviser;
		this.createTime = createTime;
		this.certificateNumber = certificateNumber;
		this.certificateDate = certificateDate;
		this.certificateAddress = certificateAddress;
		this.taxNumber = taxNumber;
		this.budgetRegister = budgetRegister;
		this.telefone = telefone;
		this.fax = fax;
		this.email = email;
		this.socialAddress = socialAddress;
		this.companyAddress = companyAddress;
		this.lawyer = lawyer;
		this.director = director;
		this.directorMobile = directorMobile;
		this.directorBirthday = directorBirthday;
		this.directorDomicile = directorDomicile;
		this.sellMan = sellMan;
		this.sellManMobile = sellManMobile;
		this.budgetOriginal = budgetOriginal;
		this.otherBusiness = otherBusiness;
		this.customer1Level1 = customer1Level1;
		this.customer1Phone = customer1Phone;
		this.customer1Percent = customer1Percent;
		this.customer2Level1 = customer2Level1;
		this.customer2Phone = customer2Phone;
		this.customer2Percent = customer2Percent;
		this.customer3Level1 = customer3Level1;
		this.customer3Phone = customer3Phone;
		this.customer3Percent = customer3Percent;
		this.customer4Level1 = customer4Level1;
		this.customer4Phone = customer4Phone;
		this.customer4Percent = customer4Percent;
		this.customer5Level1 = customer5Level1;
		this.customer5Phone = customer5Phone;
		this.customer5Percent = customer5Percent;
		this.revenue1 = revenue1;
		this.revenue2 = revenue2;
		this.percentProvide1 = percentProvide1;
		this.percentProvide2 = percentProvide2;
		this.percentProvide3 = percentProvide3;
		this.percentProvide4 = percentProvide4;
		this.productSell = productSell;
		this.product1Hot = product1Hot;
		this.product2Hot = product2Hot;
		this.product3Hot = product3Hot;
		this.product4Hot = product4Hot;
		this.product5Hot = product5Hot;
		this.product6Hot = product6Hot;
		this.farmProduct1 = farmProduct1;
		this.farmProduct1Session = farmProduct1Session;
		this.farmProduct2 = farmProduct2;
		this.farmProduct2Session = farmProduct2Session;
		this.farmProduct3 = farmProduct3;
		this.farmProduct3Session = farmProduct3Session;
		this.farmProduct4 = farmProduct4;
		this.farmProduct4Session = farmProduct4Session;
		this.totalVipCustomer = totalVipCustomer;
		this.promotionCustomers = promotionCustomers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getAdviser() {
		return this.adviser;
	}

	public void setAdviser(String adviser) {
		this.adviser = adviser;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getCertificateNumber() {
		return this.certificateNumber;
	}

	public void setCertificateNumber(String certificateNumber) {
		this.certificateNumber = certificateNumber;
	}

	public String getCertificateDate() {
		return this.certificateDate;
	}

	public void setCertificateDate(String certificateDate) {
		this.certificateDate = certificateDate;
	}

	public String getCertificateAddress() {
		return this.certificateAddress;
	}

	public void setCertificateAddress(String certificateAddress) {
		this.certificateAddress = certificateAddress;
	}

	public String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	public Integer getBudgetRegister() {
		return this.budgetRegister;
	}

	public void setBudgetRegister(Integer budgetRegister) {
		this.budgetRegister = budgetRegister;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSocialAddress() {
		return this.socialAddress;
	}

	public void setSocialAddress(String socialAddress) {
		this.socialAddress = socialAddress;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public String getLawyer() {
		return this.lawyer;
	}

	public void setLawyer(String lawyer) {
		this.lawyer = lawyer;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getDirectorMobile() {
		return this.directorMobile;
	}

	public void setDirectorMobile(String directorMobile) {
		this.directorMobile = directorMobile;
	}

	public String getDirectorBirthday() {
		return this.directorBirthday;
	}

	public void setDirectorBirthday(String directorBirthday) {
		this.directorBirthday = directorBirthday;
	}

	public String getDirectorDomicile() {
		return this.directorDomicile;
	}

	public void setDirectorDomicile(String directorDomicile) {
		this.directorDomicile = directorDomicile;
	}

	public String getSellMan() {
		return this.sellMan;
	}

	public void setSellMan(String sellMan) {
		this.sellMan = sellMan;
	}

	public String getSellManMobile() {
		return this.sellManMobile;
	}

	public void setSellManMobile(String sellManMobile) {
		this.sellManMobile = sellManMobile;
	}

	public Integer getBudgetOriginal() {
		return this.budgetOriginal;
	}

	public void setBudgetOriginal(Integer budgetOriginal) {
		this.budgetOriginal = budgetOriginal;
	}

	public String getOtherBusiness() {
		return this.otherBusiness;
	}

	public void setOtherBusiness(String otherBusiness) {
		this.otherBusiness = otherBusiness;
	}

	public String getCustomer1Level1() {
		return this.customer1Level1;
	}

	public void setCustomer1Level1(String customer1Level1) {
		this.customer1Level1 = customer1Level1;
	}

	public String getCustomer1Phone() {
		return this.customer1Phone;
	}

	public void setCustomer1Phone(String customer1Phone) {
		this.customer1Phone = customer1Phone;
	}

	public String getCustomer1Percent() {
		return this.customer1Percent;
	}

	public void setCustomer1Percent(String customer1Percent) {
		this.customer1Percent = customer1Percent;
	}

	public String getCustomer2Level1() {
		return this.customer2Level1;
	}

	public void setCustomer2Level1(String customer2Level1) {
		this.customer2Level1 = customer2Level1;
	}

	public String getCustomer2Phone() {
		return this.customer2Phone;
	}

	public void setCustomer2Phone(String customer2Phone) {
		this.customer2Phone = customer2Phone;
	}

	public String getCustomer2Percent() {
		return this.customer2Percent;
	}

	public void setCustomer2Percent(String customer2Percent) {
		this.customer2Percent = customer2Percent;
	}

	public String getCustomer3Level1() {
		return this.customer3Level1;
	}

	public void setCustomer3Level1(String customer3Level1) {
		this.customer3Level1 = customer3Level1;
	}

	public String getCustomer3Phone() {
		return this.customer3Phone;
	}

	public void setCustomer3Phone(String customer3Phone) {
		this.customer3Phone = customer3Phone;
	}

	public String getCustomer3Percent() {
		return this.customer3Percent;
	}

	public void setCustomer3Percent(String customer3Percent) {
		this.customer3Percent = customer3Percent;
	}

	public String getCustomer4Level1() {
		return this.customer4Level1;
	}

	public void setCustomer4Level1(String customer4Level1) {
		this.customer4Level1 = customer4Level1;
	}

	public String getCustomer4Phone() {
		return this.customer4Phone;
	}

	public void setCustomer4Phone(String customer4Phone) {
		this.customer4Phone = customer4Phone;
	}

	public String getCustomer4Percent() {
		return this.customer4Percent;
	}

	public void setCustomer4Percent(String customer4Percent) {
		this.customer4Percent = customer4Percent;
	}

	public String getCustomer5Level1() {
		return this.customer5Level1;
	}

	public void setCustomer5Level1(String customer5Level1) {
		this.customer5Level1 = customer5Level1;
	}

	public String getCustomer5Phone() {
		return this.customer5Phone;
	}

	public void setCustomer5Phone(String customer5Phone) {
		this.customer5Phone = customer5Phone;
	}

	public String getCustomer5Percent() {
		return this.customer5Percent;
	}

	public void setCustomer5Percent(String customer5Percent) {
		this.customer5Percent = customer5Percent;
	}

	public String getRevenue1() {
		return this.revenue1;
	}

	public void setRevenue1(String revenue1) {
		this.revenue1 = revenue1;
	}

	public String getRevenue2() {
		return this.revenue2;
	}

	public void setRevenue2(String revenue2) {
		this.revenue2 = revenue2;
	}

	public String getPercentProvide1() {
		return this.percentProvide1;
	}

	public void setPercentProvide1(String percentProvide1) {
		this.percentProvide1 = percentProvide1;
	}

	public String getPercentProvide2() {
		return this.percentProvide2;
	}

	public void setPercentProvide2(String percentProvide2) {
		this.percentProvide2 = percentProvide2;
	}

	public String getPercentProvide3() {
		return this.percentProvide3;
	}

	public void setPercentProvide3(String percentProvide3) {
		this.percentProvide3 = percentProvide3;
	}

	public String getPercentProvide4() {
		return this.percentProvide4;
	}

	public void setPercentProvide4(String percentProvide4) {
		this.percentProvide4 = percentProvide4;
	}

	public String getProductSell() {
		return this.productSell;
	}

	public void setProductSell(String productSell) {
		this.productSell = productSell;
	}

	public String getProduct1Hot() {
		return this.product1Hot;
	}

	public void setProduct1Hot(String product1Hot) {
		this.product1Hot = product1Hot;
	}

	public String getProduct2Hot() {
		return this.product2Hot;
	}

	public void setProduct2Hot(String product2Hot) {
		this.product2Hot = product2Hot;
	}

	public String getProduct3Hot() {
		return this.product3Hot;
	}

	public void setProduct3Hot(String product3Hot) {
		this.product3Hot = product3Hot;
	}

	public String getProduct4Hot() {
		return this.product4Hot;
	}

	public void setProduct4Hot(String product4Hot) {
		this.product4Hot = product4Hot;
	}

	public String getProduct5Hot() {
		return this.product5Hot;
	}

	public void setProduct5Hot(String product5Hot) {
		this.product5Hot = product5Hot;
	}

	public String getProduct6Hot() {
		return this.product6Hot;
	}

	public void setProduct6Hot(String product6Hot) {
		this.product6Hot = product6Hot;
	}

	public String getFarmProduct1() {
		return this.farmProduct1;
	}

	public void setFarmProduct1(String farmProduct1) {
		this.farmProduct1 = farmProduct1;
	}

	public String getFarmProduct1Session() {
		return this.farmProduct1Session;
	}

	public void setFarmProduct1Session(String farmProduct1Session) {
		this.farmProduct1Session = farmProduct1Session;
	}

	public String getFarmProduct2() {
		return this.farmProduct2;
	}

	public void setFarmProduct2(String farmProduct2) {
		this.farmProduct2 = farmProduct2;
	}

	public String getFarmProduct2Session() {
		return this.farmProduct2Session;
	}

	public void setFarmProduct2Session(String farmProduct2Session) {
		this.farmProduct2Session = farmProduct2Session;
	}

	public String getFarmProduct3() {
		return this.farmProduct3;
	}

	public void setFarmProduct3(String farmProduct3) {
		this.farmProduct3 = farmProduct3;
	}

	public String getFarmProduct3Session() {
		return this.farmProduct3Session;
	}

	public void setFarmProduct3Session(String farmProduct3Session) {
		this.farmProduct3Session = farmProduct3Session;
	}

	public String getFarmProduct4() {
		return this.farmProduct4;
	}

	public void setFarmProduct4(String farmProduct4) {
		this.farmProduct4 = farmProduct4;
	}

	public String getFarmProduct4Session() {
		return this.farmProduct4Session;
	}

	public void setFarmProduct4Session(String farmProduct4Session) {
		this.farmProduct4Session = farmProduct4Session;
	}

	public Integer getTotalVipCustomer() {
		return this.totalVipCustomer;
	}

	public void setTotalVipCustomer(Integer totalVipCustomer) {
		this.totalVipCustomer = totalVipCustomer;
	}

	public Set<PromotionCustomer> getPromotionCustomers() {
		return this.promotionCustomers;
	}

	public void setPromotionCustomers(Set<PromotionCustomer> promotionCustomers) {
		this.promotionCustomers = promotionCustomers;
	}

}
