package com.home.model;

// Generated Sep 5, 2016 10:48:56 PM by Hibernate Tools 3.4.0.CR1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.dhtmlx.planner.DHXEvent;
import com.dhtmlx.planner.DHXEventsManager;

/**
 * EventsHistory generated by hbm2java
 */
public class EventsHistory extends DHXEvent{
	
	public Integer id;
	public int eventId;
	public Integer employeeId;
	public Date planDateOld;
	public Date planDateNew;
	public Integer customerIdOld;
	public Integer customerIdNew;
	public String contactType;
	public String action;
	public int typeOfDay;
	public Date lastModified;
	
	//In Addition
	public String employeeName;
	public String customerNameOld;
	public String customerNameNew;
	public String contactTypeName;
	public String timelineTypeName;
	

	public int getTypeOfDay() {
		return typeOfDay;
	}

	public void setTypeOfDay(int typeOfDay) {
		this.typeOfDay = typeOfDay;
	}
	public void setTypeOfDay(String typeOfDay) {
		this.typeOfDay = Integer.parseInt(typeOfDay == "" ? "0"
				: typeOfDay);
	}
	public EventsHistory() {
	}

	public String getContactType() {
		return contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public EventsHistory(int eventId, Date planDateOld, Date planDateNew) {
		this.eventId = eventId;
		this.planDateOld = planDateOld;
		this.planDateNew = planDateNew;
	}

	public EventsHistory(int eventId, Integer employeeId, Date planDateOld,
			Date planDateNew, Integer customerIdOld, Integer customerIdNew,String contactType,
			String action,Integer typeOfDay, Date lastModified) {
		this.eventId = eventId;
		this.employeeId = employeeId;
		this.planDateOld = planDateOld;
		this.planDateNew = planDateNew;
		this.customerIdOld = customerIdOld;
		this.customerIdNew = customerIdNew;
		this.contactType = contactType;
		this.action = action;
		this.typeOfDay = typeOfDay;
		this.lastModified = lastModified;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public void setId(String id) {
		this.id = Integer.parseInt(id == "" ? "0"
				: id);
	}

	public int getEventId() {
		return this.eventId;
	}
	public void setEventId(String eventId) {
		this.eventId = Integer.parseInt(eventId == "" ? "0"
				: eventId);
	}
	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}
	public void setEmployeeId(String employeeId) {
		this.employeeId = Integer.parseInt(employeeId == "" ? "0"
				: employeeId);
	}
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public Date getPlanDateOld() {
		return this.planDateOld;
	}

	public void setPlanDateOld(Date planDateOld) {
		this.planDateOld = planDateOld;
	}

	public void setPlanDateOld(String planDateOld) {
		if (planDateOld.length() == 16)
			planDateOld = planDateOld + ":00";
		try {
			this.planDateOld = new SimpleDateFormat(
					DHXEventsManager.date_format).parse(planDateOld);
		} catch (ParseException e) {
			//e.printStackTrace();
		}
	}
	
	public Date getPlanDateNew() {
		return this.planDateNew;
	}

	public void setPlanDateNew(Date planDateNew) {
		this.planDateNew = planDateNew;
	}
	public void setPlanDateNew(String planDateNew) {
		if (planDateNew.length() == 16)
			planDateNew = planDateNew + ":00";
		try {
			this.planDateNew = new SimpleDateFormat(
					DHXEventsManager.date_format).parse(planDateNew);
		} catch (ParseException e) {
			//e.printStackTrace();
		}
	}
	public Integer getCustomerIdOld() {
		return this.customerIdOld;
	}

	public void setCustomerIdOld(Integer customerIdOld) {
		this.customerIdOld = customerIdOld;
	}

	public Integer getCustomerIdNew() {
		return this.customerIdNew;
	}

	public void setCustomerIdNew(Integer customerIdNew) {
		this.customerIdNew = customerIdNew;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}
	public void setLastModified(String lastModified) {
		if (lastModified.length() == 16)
			lastModified = lastModified + ":00";
		try {
			this.lastModified = new SimpleDateFormat(
					DHXEventsManager.date_format).parse(lastModified);
		} catch (ParseException e) {
			//e.printStackTrace();
		}
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getCustomerNameOld() {
		return customerNameOld;
	}

	public void setCustomerNameOld(String customerNameOld) {
		this.customerNameOld = customerNameOld;
	}

	public String getCustomerNameNew() {
		return customerNameNew;
	}

	public void setCustomerNameNew(String customerNameNew) {
		this.customerNameNew = customerNameNew;
	}

	public String getContactTypeName() {
		return contactTypeName;
	}

	public void setContactTypeName(String contactTypeName) {
		this.contactTypeName = contactTypeName;
	}

	public String getTimelineTypeName() {
		return timelineTypeName;
	}

	public void setTimelineTypeName(String timelineTypeName) {
		this.timelineTypeName = timelineTypeName;
	}
	
}
