package com.home.model;

// Generated Sep 5, 2016 10:29:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventsNote generated by hbm2java
 */
public class EventsNote implements java.io.Serializable {

	private Integer id;
	private String ECode;
	private String ENote;

	public EventsNote() {
	}

	public EventsNote(String ECode) {
		this.ECode = ECode;
	}

	public EventsNote(String ECode, String ENote) {
		this.ECode = ECode;
		this.ENote = ENote;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getECode() {
		return this.ECode;
	}

	public void setECode(String ECode) {
		this.ECode = ECode;
	}

	public String getENote() {
		return this.ENote;
	}

	public void setENote(String ENote) {
		this.ENote = ENote;
	}

}
