package com.home.model;

// Generated Sep 5, 2016 10:29:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EventsHistory generated by hbm2java
 */
public class EventsHistory implements java.io.Serializable {

	private Integer id;
	private int eventId;
	private Integer employeeId;
	private Date planDateOld;
	private Date planDateNew;
	private Integer customerIdOld;
	private Integer customerIdNew;

	public EventsHistory() {
	}

	public EventsHistory(int eventId, Date planDateOld, Date planDateNew) {
		this.eventId = eventId;
		this.planDateOld = planDateOld;
		this.planDateNew = planDateNew;
	}

	public EventsHistory(int eventId, Integer employeeId, Date planDateOld,
			Date planDateNew, Integer customerIdOld, Integer customerIdNew) {
		this.eventId = eventId;
		this.employeeId = employeeId;
		this.planDateOld = planDateOld;
		this.planDateNew = planDateNew;
		this.customerIdOld = customerIdOld;
		this.customerIdNew = customerIdNew;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public Date getPlanDateOld() {
		return this.planDateOld;
	}

	public void setPlanDateOld(Date planDateOld) {
		this.planDateOld = planDateOld;
	}

	public Date getPlanDateNew() {
		return this.planDateNew;
	}

	public void setPlanDateNew(Date planDateNew) {
		this.planDateNew = planDateNew;
	}

	public Integer getCustomerIdOld() {
		return this.customerIdOld;
	}

	public void setCustomerIdOld(Integer customerIdOld) {
		this.customerIdOld = customerIdOld;
	}

	public Integer getCustomerIdNew() {
		return this.customerIdNew;
	}

	public void setCustomerIdNew(Integer customerIdNew) {
		this.customerIdNew = customerIdNew;
	}

}
