package com.home.model;

// Generated Jan 12, 2016 11:20:58 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Gift generated by hbm2java
 */
public class Gift implements java.io.Serializable {

	private Integer id;
	private String giftName;
	private Set<PromotionCustomer> promotionCustomers = new HashSet<PromotionCustomer>(
			0);

	public Gift() {
	}

	public Gift(String giftName, Set<PromotionCustomer> promotionCustomers) {
		this.giftName = giftName;
		this.promotionCustomers = promotionCustomers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGiftName() {
		return this.giftName;
	}

	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}

	public Set<PromotionCustomer> getPromotionCustomers() {
		return this.promotionCustomers;
	}

	public void setPromotionCustomers(Set<PromotionCustomer> promotionCustomers) {
		this.promotionCustomers = promotionCustomers;
	}

}
