package com.home.model;

// Generated Mar 17, 2016 9:59:50 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupCustomer generated by hbm2java
 */
public class GroupCustomerDetail implements java.io.Serializable {
	private Integer id;
	private Integer group_customer_id;
	private String groupName;
	private String note;
	
	public GroupCustomerDetail() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public GroupCustomerDetail(Integer id, Integer group_customer_id,
			String groupName, String note) {
		super();
		this.id = id;
		this.group_customer_id = group_customer_id;
		this.groupName = groupName;
		this.note = note;
	}

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getGroup_customer_id() {
		return group_customer_id;
	}
	public void setGroup_customer_id(Integer group_customer_id) {
		this.group_customer_id = group_customer_id;
	}
	public String getGroupName() {
		return groupName;
	}
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	
	
}
