package com.home.model;

// Generated Mar 17, 2016 9:59:50 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupCustomer generated by hbm2java
 */
public class GroupCustomer implements java.io.Serializable {
	private Integer id;
	private String groupName;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Promotion> promotions = new HashSet<Promotion>(0);

	public GroupCustomer() {
	}

	public GroupCustomer(String groupName, Set<Customer> customers, Set<Promotion> promotions) {
		this.groupName = groupName;
		this.customers = customers;
		this.promotions = promotions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	public Set<Promotion> getPromotions() {
		return this.promotions;
	}

	public void setPromotions(Set<Promotion> promotions) {
		this.promotions = promotions;
	}

}
