package com.home.model;

// Generated Apr 22, 2016 10:24:41 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceType generated by hbm2java
 */
public class InvoiceType implements java.io.Serializable {

	private Integer id;
	private String invoiceType;
	private String description;
	private Set<Statistic> statistics = new HashSet<Statistic>(0);

	public InvoiceType() {
	}
	
	public InvoiceType(Integer id, String invoiceType) {
		super();
		this.id = id;
		this.invoiceType = invoiceType;
	}

	public InvoiceType(String invoiceType, String description, Set<Statistic> statistics) {
		this.invoiceType = invoiceType;
		this.description = description;
		this.statistics = statistics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Statistic> getStatistics() {
		return this.statistics;
	}

	public void setStatistics(Set<Statistic> statistics) {
		this.statistics = statistics;
	}

}
