package com.home.model;

// Generated Feb 24, 2016 9:17:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String productCode;
	private String productType;
	private String productName;
	private String description;
	private BigDecimal unitPrice;
	private Integer minQuantity;
	private Integer maxQuantity;
	private Date exportDate;
	private Date launchDate;
	private Set<PromotionProduct> promotionProducts = new HashSet<PromotionProduct>(0);

	public Product() {
	}

	public Product(Category category, String productCode, String productType, String productName, String description, BigDecimal unitPrice, Integer minQuantity, Integer maxQuantity, Date exportDate,
			Date launchDate, Set<PromotionProduct> promotionProducts) {
		this.category = category;
		this.productCode = productCode;
		this.productType = productType;
		this.productName = productName;
		this.description = description;
		this.unitPrice = unitPrice;
		this.minQuantity = minQuantity;
		this.maxQuantity = maxQuantity;
		this.exportDate = exportDate;
		this.launchDate = launchDate;
		this.promotionProducts = promotionProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Integer getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(Integer minQuantity) {
		this.minQuantity = minQuantity;
	}

	public Integer getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(Integer maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

	public Date getExportDate() {
		return this.exportDate;
	}

	public void setExportDate(Date exportDate) {
		this.exportDate = exportDate;
	}

	public Date getLaunchDate() {
		return this.launchDate;
	}

	public void setLaunchDate(Date launchDate) {
		this.launchDate = launchDate;
	}

	public Set<PromotionProduct> getPromotionProducts() {
		return this.promotionProducts;
	}

	public void setPromotionProducts(Set<PromotionProduct> promotionProducts) {
		this.promotionProducts = promotionProducts;
	}

}
