package com.home.model;

// Generated Feb 24, 2016 9:17:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String productCode;
	private String productName;
	private String description;
	private BigDecimal unitPrice;
	private Integer quantity;
	private Integer point;
	private Date exportDate;
	private Integer category_id;
	private Set<PromotionProduct> promotionProducts = new HashSet<PromotionProduct>(0);
	private Integer totalBox;
	
	public Product() {
	}

	public Product(Category category, String productCode, String productName, String description, BigDecimal unitPrice, Integer quantity, Integer point, Date exportDate,
			Set<PromotionProduct> promotionProducts) {
		this.category = category;
		this.productCode = productCode;
		this.productName = productName;
		this.description = description;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.point = point;
		this.exportDate = exportDate;
		this.promotionProducts = promotionProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}


	public Date getExportDate() {
		return this.exportDate;
	}

	public void setExportDate(Date exportDate) {
		this.exportDate = exportDate;
	}

	public Set<PromotionProduct> getPromotionProducts() {
		return this.promotionProducts;
	}

	public void setPromotionProducts(Set<PromotionProduct> promotionProducts) {
		this.promotionProducts = promotionProducts;
	}

	public Integer getCategory_id() {
		return category_id;
	}

	public void setCategory_id(Integer category_id) {
		this.category_id = category_id;
	}
	public Integer getPoint() {
		return point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}
	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public Integer getTotalBox() {
		return totalBox;
	}

	public void setTotalBox(Integer totalBox) {
		this.totalBox = totalBox;
	}
}
