package com.home.model;

// Generated Jan 12, 2016 11:20:58 PM by Hibernate Tools 4.0.0

/**
 * PromotionCustomerProduct generated by hbm2java
 */
public class PromotionCustomerProduct implements java.io.Serializable {

	private PromotionCustomerProductId id;
	private PromotionCustomer promotionCustomer;
	private PromotionProduct promotionProduct;

	public PromotionCustomerProduct() {
	}

	public PromotionCustomerProduct(PromotionCustomerProductId id,
			PromotionCustomer promotionCustomer,
			PromotionProduct promotionProduct) {
		this.id = id;
		this.promotionCustomer = promotionCustomer;
		this.promotionProduct = promotionProduct;
	}

	public PromotionCustomerProductId getId() {
		return this.id;
	}

	public void setId(PromotionCustomerProductId id) {
		this.id = id;
	}

	public PromotionCustomer getPromotionCustomer() {
		return this.promotionCustomer;
	}

	public void setPromotionCustomer(PromotionCustomer promotionCustomer) {
		this.promotionCustomer = promotionCustomer;
	}

	public PromotionProduct getPromotionProduct() {
		return this.promotionProduct;
	}

	public void setPromotionProduct(PromotionProduct promotionProduct) {
		this.promotionProduct = promotionProduct;
	}

}
