package com.home.model;

// Generated Jan 27, 2016 10:24:28 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PromotionProduct generated by hbm2java
 */
public class PromotionProduct implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Promotion promotion;
	private Set<PromotionCustomerProduct> promotionCustomerProducts = new HashSet<PromotionCustomerProduct>(0);

	public PromotionProduct() {
	}

	public PromotionProduct(Product product, Promotion promotion) {
		this.product = product;
		this.promotion = promotion;
	}

	public PromotionProduct(Product product, Promotion promotion, Set<PromotionCustomerProduct> promotionCustomerProducts) {
		this.product = product;
		this.promotion = promotion;
		this.promotionCustomerProducts = promotionCustomerProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Set<PromotionCustomerProduct> getPromotionCustomerProducts() {
		return this.promotionCustomerProducts;
	}

	public void setPromotionCustomerProducts(Set<PromotionCustomerProduct> promotionCustomerProducts) {
		this.promotionCustomerProducts = promotionCustomerProducts;
	}

}
