package com.home.model;

// Generated Jan 12, 2016 11:20:58 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private Integer id;
	private String promotionName;
	private Date startDate;
	private Date endDate;
	private String remarks;
	private Boolean status;
	private Set<PromotionCustomer> promotionCustomers = new HashSet<PromotionCustomer>(
			0);
	private Set<PromotionProduct> promotionProducts = new HashSet<PromotionProduct>(
			0);

	public Promotion() {
	}

	public Promotion(String promotionName, Date startDate, Date endDate,
			String remarks, Boolean status,
			Set<PromotionCustomer> promotionCustomers,
			Set<PromotionProduct> promotionProducts) {
		this.promotionName = promotionName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.remarks = remarks;
		this.status = status;
		this.promotionCustomers = promotionCustomers;
		this.promotionProducts = promotionProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPromotionName() {
		return this.promotionName;
	}

	public void setPromotionName(String promotionName) {
		this.promotionName = promotionName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<PromotionCustomer> getPromotionCustomers() {
		return this.promotionCustomers;
	}

	public void setPromotionCustomers(Set<PromotionCustomer> promotionCustomers) {
		this.promotionCustomers = promotionCustomers;
	}

	public Set<PromotionProduct> getPromotionProducts() {
		return this.promotionProducts;
	}

	public void setPromotionProducts(Set<PromotionProduct> promotionProducts) {
		this.promotionProducts = promotionProducts;
	}

}
