package com.home.model;

// Generated Jan 27, 2016 10:24:28 PM by Hibernate Tools 4.3.1

/**
 * PromotionCustomerProductId generated by hbm2java
 */
public class PromotionCustomerProductId implements java.io.Serializable {

	private int promotionProductId;
	private int promotionCustomerId;
	private Integer maxPoint;

	public PromotionCustomerProductId() {
	}

	public PromotionCustomerProductId(int promotionProductId, int promotionCustomerId) {
		this.promotionProductId = promotionProductId;
		this.promotionCustomerId = promotionCustomerId;
	}

	public PromotionCustomerProductId(int promotionProductId, int promotionCustomerId, Integer maxPoint) {
		this.promotionProductId = promotionProductId;
		this.promotionCustomerId = promotionCustomerId;
		this.maxPoint = maxPoint;
	}

	public int getPromotionProductId() {
		return this.promotionProductId;
	}

	public void setPromotionProductId(int promotionProductId) {
		this.promotionProductId = promotionProductId;
	}

	public int getPromotionCustomerId() {
		return this.promotionCustomerId;
	}

	public void setPromotionCustomerId(int promotionCustomerId) {
		this.promotionCustomerId = promotionCustomerId;
	}

	public Integer getMaxPoint() {
		return this.maxPoint;
	}

	public void setMaxPoint(Integer maxPoint) {
		this.maxPoint = maxPoint;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotionCustomerProductId))
			return false;
		PromotionCustomerProductId castOther = (PromotionCustomerProductId) other;

		return (this.getPromotionProductId() == castOther.getPromotionProductId()) && (this.getPromotionCustomerId() == castOther.getPromotionCustomerId())
				&& ((this.getMaxPoint() == castOther.getMaxPoint()) || (this.getMaxPoint() != null && castOther.getMaxPoint() != null && this.getMaxPoint().equals(castOther.getMaxPoint())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPromotionProductId();
		result = 37 * result + this.getPromotionCustomerId();
		result = 37 * result + (getMaxPoint() == null ? 0 : this.getMaxPoint().hashCode());
		return result;
	}

}
