package com.home.model;

// Generated Feb 24, 2016 9:17:27 PM by Hibernate Tools 4.3.1

/**
 * PromotionGift generated by hbm2java
 */
public class PromotionGift implements java.io.Serializable {

	private Integer id;
	private Gift gift;
	private Promotion promotion;
	private Integer maxQuantity;
	private Integer maxPoint;

	public PromotionGift() {
	}

	public PromotionGift(Gift gift, Promotion promotion) {
		this.gift = gift;
		this.promotion = promotion;
	}

	public PromotionGift(Gift gift, Promotion promotion, Integer maxQuantity, Integer maxPoint) {
		this.gift = gift;
		this.promotion = promotion;
		this.maxQuantity = maxQuantity;
		this.maxPoint = maxPoint;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Gift getGift() {
		return this.gift;
	}

	public void setGift(Gift gift) {
		this.gift = gift;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Integer getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(Integer maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

	public Integer getMaxPoint() {
		return this.maxPoint;
	}

	public void setMaxPoint(Integer maxPoint) {
		this.maxPoint = maxPoint;
	}

}
