package com.home.model;

// Generated Jan 12, 2016 11:20:58 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PromotionProduct generated by hbm2java
 */
public class PromotionProduct implements java.io.Serializable {

	private Integer id;
	private Promotion promotion;
	private Product product;
	private Set<PromotionCustomerProduct> promotionCustomerProducts = new HashSet<PromotionCustomerProduct>(
			0);

	public PromotionProduct() {
	}

	public PromotionProduct(Promotion promotion, Product product) {
		this.promotion = promotion;
		this.product = product;
	}

	public PromotionProduct(Promotion promotion, Product product,
			Set<PromotionCustomerProduct> promotionCustomerProducts) {
		this.promotion = promotion;
		this.product = product;
		this.promotionCustomerProducts = promotionCustomerProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Set<PromotionCustomerProduct> getPromotionCustomerProducts() {
		return this.promotionCustomerProducts;
	}

	public void setPromotionCustomerProducts(
			Set<PromotionCustomerProduct> promotionCustomerProducts) {
		this.promotionCustomerProducts = promotionCustomerProducts;
	}

}
