package com.home.model;

// Generated Mar 9, 2016 8:44:07 PM by Hibernate Tools 4.3.1

/**
 * RegisterGift generated by hbm2java
 */
public class RegisterGift implements java.io.Serializable {

	private Integer id;
	private PromotionGift promotionGift;
	private PromotionRegister promotionRegister;

	public RegisterGift() {
	}

	public RegisterGift(PromotionGift promotionGift, PromotionRegister promotionRegister) {
		this.promotionGift = promotionGift;
		this.promotionRegister = promotionRegister;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PromotionGift getPromotionGift() {
		return this.promotionGift;
	}

	public void setPromotionGift(PromotionGift promotionGift) {
		this.promotionGift = promotionGift;
	}

	public PromotionRegister getPromotionRegister() {
		return this.promotionRegister;
	}

	public void setPromotionRegister(PromotionRegister promotionRegister) {
		this.promotionRegister = promotionRegister;
	}

}
