package com.home.model;

// Generated Mar 9, 2016 8:44:07 PM by Hibernate Tools 4.3.1

/**
 * RegisterGift generated by hbm2java
 */
public class RegisterGift implements java.io.Serializable {

	private Integer id;
	private PromotionGift promotionGift;
	private PromotionRegister promotionRegister;
	private Integer p_gift_id;
	private boolean applyAll;
	private Integer total;

	public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public boolean getApplyAll() {
		return applyAll;
	}

	public void setApplyAll(boolean applyAll) {
		this.applyAll = applyAll;
	}

	public Integer getP_gift_id() {
		return p_gift_id;
	}

	public void setP_gift_id(Integer p_gift_id) {
		this.p_gift_id = p_gift_id;
	}

	public RegisterGift() {
	}

	public RegisterGift(PromotionGift promotionGift, PromotionRegister promotionRegister) {
		this.promotionGift = promotionGift;
		this.promotionRegister = promotionRegister;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PromotionGift getPromotionGift() {
		return this.promotionGift;
	}

	public void setPromotionGift(PromotionGift promotionGift) {
		this.promotionGift = promotionGift;
	}

	public PromotionRegister getPromotionRegister() {
		return this.promotionRegister;
	}

	public void setPromotionRegister(PromotionRegister promotionRegister) {
		this.promotionRegister = promotionRegister;
	}

}
