package com.home.model;

// Generated Apr 22, 2016 10:24:41 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Statistic generated by hbm2java
 */
public class Statistic implements java.io.Serializable {

	public Integer id;
	public Customer customerByCustomerCodeLevel1;
	public Customer customerByCustomerCodeLevel2;
	public InvoiceType invoiceType;
	public Product product;
	public User user;
	public Date dateReceived;
	public Float totalBox;
	public Integer quantity;
	public BigDecimal total;
	private int no;

	public Statistic() {
	}

	public Statistic(Customer customerByCustomerCodeLevel1, Customer customerByCustomerCodeLevel2, InvoiceType invoiceType, Product product, User user, Date dateReceived, Float totalBox,
			Integer quantity, BigDecimal total) {
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
		this.invoiceType = invoiceType;
		this.product = product;
		this.user = user;
		this.dateReceived = dateReceived;
		this.totalBox = totalBox;
		this.quantity = quantity;
		this.total = total;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomerByCustomerCodeLevel1() {
		return this.customerByCustomerCodeLevel1;
	}

	public void setCustomerByCustomerCodeLevel1(Customer customerByCustomerCodeLevel1) {
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
	}

	public Customer getCustomerByCustomerCodeLevel2() {
		return this.customerByCustomerCodeLevel2;
	}

	public void setCustomerByCustomerCodeLevel2(Customer customerByCustomerCodeLevel2) {
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
	}

	public InvoiceType getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(InvoiceType invoiceType) {
		this.invoiceType = invoiceType;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateReceived() {
		return this.dateReceived;
	}

	public void setDateReceived(Date dateReceived) {
		this.dateReceived = dateReceived;
	}

	public Float getTotalBox() {
		return this.totalBox;
	}

	public void setTotalBox(Float totalBox) {
		this.totalBox = totalBox;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public int getNo() {
		return no;
	}

	public void setNo(int no) {
		this.no = no;
	}
}
