package com.home.model;

// Generated Feb 29, 2016 9:07:10 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Statistic generated by hbm2java
 */
public class Statistic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Customer customerByCustomerCodeLevel1;
	private Customer customerByCustomerCodeLevel2;
	private User user;
	private Date dateReceived;
	private String productCode;
	private String categoryName;
	private String productName;
	private Integer totalBox;
	private Integer quantiy;
	private BigDecimal unitPrice;
	private BigDecimal total;

	public Statistic() {
	}

	public Statistic(int id) {
		this.id = id;
	}

	public Statistic(int id, Customer customerByCustomerCodeLevel1, Customer customerByCustomerCodeLevel2, User user, Date dateReceived, String productCode, String categoryName, String productName,
			Integer totalBox, Integer quantiy, BigDecimal unitPrice, BigDecimal total) {
		this.id = id;
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
		this.user = user;
		this.dateReceived = dateReceived;
		this.productCode = productCode;
		this.categoryName = categoryName;
		this.productName = productName;
		this.totalBox = totalBox;
		this.quantiy = quantiy;
		this.unitPrice = unitPrice;
		this.total = total;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomerByCustomerCodeLevel1() {
		return this.customerByCustomerCodeLevel1;
	}

	public void setCustomerByCustomerCodeLevel1(Customer customerByCustomerCodeLevel1) {
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
	}

	public Customer getCustomerByCustomerCodeLevel2() {
		return this.customerByCustomerCodeLevel2;
	}

	public void setCustomerByCustomerCodeLevel2(Customer customerByCustomerCodeLevel2) {
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateReceived() {
		return this.dateReceived;
	}

	public void setDateReceived(Date dateReceived) {
		this.dateReceived = dateReceived;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getTotalBox() {
		return this.totalBox;
	}

	public void setTotalBox(Integer totalBox) {
		this.totalBox = totalBox;
	}

	public Integer getQuantiy() {
		return this.quantiy;
	}

	public void setQuantiy(Integer quantiy) {
		this.quantiy = quantiy;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

}
