package com.home.model;

// Generated Feb 24, 2016 9:17:27 PM by Hibernate Tools 4.3.1

/**
 * StatisticId generated by hbm2java
 */
public class StatisticId implements java.io.Serializable {

	private int id;
	private String customerCodeLevel1;
	private String customerCodeLevel2;

	public StatisticId() {
	}

	public StatisticId(int id, String customerCodeLevel1, String customerCodeLevel2) {
		this.id = id;
		this.customerCodeLevel1 = customerCodeLevel1;
		this.customerCodeLevel2 = customerCodeLevel2;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCustomerCodeLevel1() {
		return this.customerCodeLevel1;
	}

	public void setCustomerCodeLevel1(String customerCodeLevel1) {
		this.customerCodeLevel1 = customerCodeLevel1;
	}

	public String getCustomerCodeLevel2() {
		return this.customerCodeLevel2;
	}

	public void setCustomerCodeLevel2(String customerCodeLevel2) {
		this.customerCodeLevel2 = customerCodeLevel2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StatisticId))
			return false;
		StatisticId castOther = (StatisticId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCustomerCodeLevel1() == castOther.getCustomerCodeLevel1()) || (this.getCustomerCodeLevel1() != null && castOther.getCustomerCodeLevel1() != null && this
						.getCustomerCodeLevel1().equals(castOther.getCustomerCodeLevel1())))
				&& ((this.getCustomerCodeLevel2() == castOther.getCustomerCodeLevel2()) || (this.getCustomerCodeLevel2() != null && castOther.getCustomerCodeLevel2() != null && this
						.getCustomerCodeLevel2().equals(castOther.getCustomerCodeLevel2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getCustomerCodeLevel1() == null ? 0 : this.getCustomerCodeLevel1().hashCode());
		result = 37 * result + (getCustomerCodeLevel2() == null ? 0 : this.getCustomerCodeLevel2().hashCode());
		return result;
	}

}
