package com.home.model;

// Generated Mar 1, 2016 10:27:23 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Statistic generated by hbm2java
 */
public class Statistic implements java.io.Serializable {

	private Integer id;
	private Customer customerByCustomerCodeLevel1;
	private Customer customerByCustomerCodeLevel2;
	private Product product;
	private Uom uom;
	private User user;
	private Date dateReceived;
	private Integer quantity;
	private BigDecimal unitPrice;
	private BigDecimal total;
	private Integer quantiy;

	public Statistic() {
	}

	public Statistic(Customer customerByCustomerCodeLevel1, Customer customerByCustomerCodeLevel2, Product product, Uom uom, User user, Date dateReceived, Integer quantity, BigDecimal unitPrice,
			BigDecimal total, Integer quantiy) {
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
		this.product = product;
		this.uom = uom;
		this.user = user;
		this.dateReceived = dateReceived;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.total = total;
		this.quantiy = quantiy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomerByCustomerCodeLevel1() {
		return this.customerByCustomerCodeLevel1;
	}

	public void setCustomerByCustomerCodeLevel1(Customer customerByCustomerCodeLevel1) {
		this.customerByCustomerCodeLevel1 = customerByCustomerCodeLevel1;
	}

	public Customer getCustomerByCustomerCodeLevel2() {
		return this.customerByCustomerCodeLevel2;
	}

	public void setCustomerByCustomerCodeLevel2(Customer customerByCustomerCodeLevel2) {
		this.customerByCustomerCodeLevel2 = customerByCustomerCodeLevel2;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Uom getUom() {
		return this.uom;
	}

	public void setUom(Uom uom) {
		this.uom = uom;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateReceived() {
		return this.dateReceived;
	}

	public void setDateReceived(Date dateReceived) {
		this.dateReceived = dateReceived;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public Integer getQuantiy() {
		return this.quantiy;
	}

	public void setQuantiy(Integer quantiy) {
		this.quantiy = quantiy;
	}

}
