package com.home.model;

// Generated Sep 19, 2016 11:34:17 PM by Hibernate Tools 4.3.1

/**
 * TimelineType generated by hbm2java
 */
public class TimelineType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String timelineTypeKey;
	private String timelineTypeName;

	public TimelineType() {
	}

	public TimelineType(String timelineTypeKey, String timelineTypeName) {
		this.timelineTypeKey = timelineTypeKey;
		this.timelineTypeName = timelineTypeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTimelineTypeKey() {
		return this.timelineTypeKey;
	}

	public void setTimelineTypeKey(String timelineTypeKey) {
		this.timelineTypeKey = timelineTypeKey;
	}

	public String getTimelineTypeName() {
		return this.timelineTypeName;
	}

	public void setTimelineTypeName(String timelineTypeName) {
		this.timelineTypeName = timelineTypeName;
	}

}
