package com.home.model;

// Generated Feb 24, 2016 9:17:27 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * WorkingPlan generated by hbm2java
 */
public class WorkingPlan implements java.io.Serializable {

	private Integer id;
	private User user;
	private String planName;
	private String planDescription;
	private String workingType;
	private String location;
	private Date planStart;
	private Date planEnd;
	private Date createTime;
	private Date updateTime;
	private short planDone;

	public WorkingPlan() {
	}

	public WorkingPlan(User user, short planDone) {
		this.user = user;
		this.planDone = planDone;
	}

	public WorkingPlan(User user, String planName, String planDescription, String workingType, String location, Date planStart, Date planEnd, Date createTime, Date updateTime, short planDone) {
		this.user = user;
		this.planName = planName;
		this.planDescription = planDescription;
		this.workingType = workingType;
		this.location = location;
		this.planStart = planStart;
		this.planEnd = planEnd;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.planDone = planDone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public String getPlanDescription() {
		return this.planDescription;
	}

	public void setPlanDescription(String planDescription) {
		this.planDescription = planDescription;
	}

	public String getWorkingType() {
		return this.workingType;
	}

	public void setWorkingType(String workingType) {
		this.workingType = workingType;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getPlanStart() {
		return this.planStart;
	}

	public void setPlanStart(Date planStart) {
		this.planStart = planStart;
	}

	public Date getPlanEnd() {
		return this.planEnd;
	}

	public void setPlanEnd(Date planEnd) {
		this.planEnd = planEnd;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public short getPlanDone() {
		return this.planDone;
	}

	public void setPlanDone(short planDone) {
		this.planDone = planDone;
	}

}
