package com.home.entities;

// Generated Mar 14, 2016 8:28:37 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Statistic generated by hbm2java
 */
public class StatisticCustom implements java.io.Serializable {

	private int custLevel1Id;
	private int custLevel2Id;
	private int empId;
	private Date fromDate;
	private Date toDate;

	public StatisticCustom() {
	}

	public StatisticCustom(int custLevel1Id, int custLevel2Id, int empId, Date fromDate, Date toDate) {
		super();
		this.custLevel1Id = custLevel1Id;
		this.custLevel2Id = custLevel2Id;
		this.empId = empId;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public int getCustLevel1Id() {
		return custLevel1Id;
	}

	public void setCustLevel1Id(int custLevel1Id) {
		this.custLevel1Id = custLevel1Id;
	}

	public int getCustLevel2Id() {
		return custLevel2Id;
	}

	public void setCustLevel2Id(int custLevel2Id) {
		this.custLevel2Id = custLevel2Id;
	}

	public int getEmpId() {
		return empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	

}
